// *********************************************************************
//   Custom DPA Handler code template                                  *
// *********************************************************************
// Copyright (c) MICRORISC s.r.o.
//
// File:    $RCSfile: CustomDpaHandler-Template-Node.c,v $
// Version: $Revision: 1.23 $
// Date:    $Date: 2024/01/22 14:51:08 $
//
// Revision history:
//   2023/03/07  Release for DPA 4.30
//   2022/10/05  Release for DPA 4.18
//   2022/02/24  Release for DPA 4.17
//   2021/08/20  Release for DPA 4.16
//   2020/09/03  Release for DPA 4.15
//   2020/02/27  Release for DPA 4.13
//   2019/01/10  Release for DPA 4.00
//   2017/08/14  Release for DPA 3.01
//   2017/03/13  Release for DPA 3.00
//   2015/08/05  Release for DPA 2.20
//   2014/10/31  Release for DPA 2.10
//   2014/04/30  Release for DPA 2.00
//
// *********************************************************************

// Online DPA documentation https://doc.iqrf.org/DpaTechGuide/

// Default IQRF include (modify the path according to your setup)
#include "IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "DPAcustomHandler.h"

// Uncomment the following includes if the respective component is needed
// IQRF standards header (modify the path according to your setup)
//#include "IQRFstandard.h"
//#include "IQRF_HWPID.h"
//#include "NFC.c"

//############################################################################################

// Place for global variables shared among CustomDpaHandler() and other function, otherwise local [static] variables are recommended
// example: uns8 globalCounter;

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
// https://doc.iqrf.org/DpaTechGuide/pages/custom-dpa-handler.html
#define PIN1 2
#define PIN2 3
#define PIN3 5

bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Place for local static variables used only within CustomDpaHandler() among more events
  // example: static bit interruptOccured;

  // Detect DPA event to handle (unused event handlers can be commented out or even deleted)
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the �empty� return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.
      // https://doc.iqrf.org/DpaTechGuide/pages/EventInterrupt.html
      return Carry;

      // -------------------------------------------------
    case DpaEvent_Idle:
      // Do a quick background work when RF packet is not received
      // https://doc.iqrf.org/DpaTechGuide/pages/idle.html
      break;

      // -------------------------------------------------
    case DpaEvent_Reset:
      // Called after module is reset
      // https://doc.iqrf.org/DpaTechGuide/pages/ResetEvent.html

      //goto DpaHandleReturnTRUE; // return TRUE only if you handle node bonding/unbonding
      break;

      // -------------------------------------------------
#if defined( DpaEvent_BondingButton )
    case DpaEvent_BondingButton:
      // Called to allow a bonding button customization
      // https://doc.iqrf.org/DpaTechGuide/pages/bondingbutton.html

      //goto DpaHandleReturnTRUE; // return TRUE to handle bonding button
      break;
#endif

      // -------------------------------------------------
    case DpaEvent_Indicate:
      // Called to allow a customization of the device indication
      // https://doc.iqrf.org/DpaTechGuide/pages/IndicateEvent.html

      //goto DpaHandleReturnTRUE; // return TRUE to skip default indication
      break;

      // -------------------------------------------------
    case DpaEvent_Init:
      // Do a one time initialization before main loop starts
      // https://doc.iqrf.org/DpaTechGuide/pages/init.html
        TRISC.PIN1 = 0;
	    TRISC.PIN2 = 0;
        TRISC.PIN3 = 0;
	    LATC.PIN1 = 0;
	    LATC.PIN2 = 0;
	    LATC.PIN3 = 0;
      break;

      // -------------------------------------------------
    case DpaEvent_ReceiveDpaRequest:
      // Called after DPA request was received
      // https://doc.iqrf.org/DpaTechGuide/pages/receivedparequest.html

      //goto DpaHandleReturnTRUE; // return TRUE to skip default processing
      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSendingDpaResponse:
      // Called before sending DPA response back to originator of DPA response
      // https://doc.iqrf.org/DpaTechGuide/pages/beforesendingdparesponse.html
      break;

      // -------------------------------------------------
    case DpaEvent_Notification:
        if ( _PNUM == PNUM_RAM && _PCMD == CMD_RAM_WRITE )
        {
            // w pamięci ram od bajtu 0 zapisana jest sekwencja
            // kończy się na bajcie o wartości 0
            // przy miganiu zakładany jest stan 0 na początku i końcu
            // syntax w bajtach kolejno (max 55!:
            // <kod> <czas czekania (ms)> <mnożnik opóźnienia> (<mnożnik świecenia przy miganiu>) (<ilość przy miganiu>) ... 0x00 / koniec
            // kody:
            // 0x00 - koniec
            // 0x01 - wylacz pin 1
            // 0x02 - wlacz pin 1
            // 0x03 - migaj pin 1
            // 0x04 - wylacz pin 2
            // 0x05 - wlacz pin 2
            // 0x06 - migaj pin 2
            // 0x07 - wylacz pin 3
            // 0x08 - wlacz pin 3
            // 0x09 - migaj pin 3

            // W przyszłości możnaby skompresować rozkazy w przypadku potrzeby zmieszczenia większej ilości

            uns8 index = 0;
            while (PeripheralRam[index] != 0x00 && index < 52) {
                if (index >= 50 && (PeripheralRam[index] == 0x03 || PeripheralRam[index] == 0x06 || PeripheralRam[index] == 0x09)) {
                    return 0;
                }

                switch (PeripheralRam[index]) {
                    case 0x01:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN1 = 0;
                        index += 3;
                    }
                        break;
                    case 0x02:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN1 = 1;
                        index += 3;
                    }
                        break;
                    case 0x03:
                    {
                        LATC.PIN1 = 0;
                        uns8 blinks = 0;
                        while (blinks < PeripheralRam[index + 4]) {
                            uns8 counter = 0;
                            while (counter < PeripheralRam[index + 2]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN1 = 1;
                            counter = 0;
                            while (counter < PeripheralRam[index + 3]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN1 = 0;
                            blinks++;
                        }
                        index += 5;
                    }
                        break;
                    case 0x04:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN2 = 0;
                        index += 3;
                    }
                        break;
                    case 0x05:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN2 = 1;
                        index += 3;
                    }
                        break;
                    case 0x06:
                    {
                        LATC.PIN2 = 0;
                        uns8 blinks = 0;
                        while (blinks < PeripheralRam[index + 4]) {
                            uns8 counter = 0;
                            while (counter < PeripheralRam[index + 2]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN2 = 1;
                            counter = 0;
                            while (counter < PeripheralRam[index + 3]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN2 = 0;
                            blinks++;
                        }
                        index += 5;
                    }
                        break;
                    case 0x07:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN3 = 0;
                        index += 3;
                    }
                        break;
                    case 0x08:
                    {
                        uns8 counter = 0;
                        while (counter < PeripheralRam[index + 2]) {
                            waitMS(PeripheralRam[index + 1]);
                            counter++;
                        }
                        LATC.PIN3 = 1;
                        index += 3;
                    }
                        break;
                    case 0x09:
                    {
                        LATC.PIN3 = 0;
                        uns8 blinks = 0;
                        while (blinks < PeripheralRam[index + 4]) {
                            uns8 counter = 0;
                            while (counter < PeripheralRam[index + 2]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN3 = 1;
                            counter = 0;
                            while (counter < PeripheralRam[index + 3]) {
                                waitMS(PeripheralRam[index + 1]);
                                counter++;
                            }
                            LATC.PIN3 = 0;
                            blinks++;
                        }
                        index += 5;
                    }
                        break;
                    default:
                        return 0;
                }
            }
        }
      // Called after DPA request was processed and after DPA response was sent
      // https://doc.iqrf.org/DpaTechGuide/pages/notification.html
      break;

      // -------------------------------------------------
    case DpaEvent_AfterRouting:
      // Called after Notification and after routing of the DPA response was finished
      // https://doc.iqrf.org/DpaTechGuide/pages/afterrouting.html
      break;

      // -------------------------------------------------
    case DpaEvent_FrcValue:
      // Called to get FRC value
      // https://doc.iqrf.org/DpaTechGuide/pages/frcvalue.html
      break;

      // -------------------------------------------------
    case DpaEvent_FrcResponseTime:
      // Called to get FRC response time
      // https://doc.iqrf.org/DpaTechGuide/pages/frcresponsetime.html
      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSleep:
      // Called before going to sleep
      // https://doc.iqrf.org/DpaTechGuide/pages/beforesleep.html
      break;

      // -------------------------------------------------
    case DpaEvent_AfterSleep:
      // Called after woken up after sleep
      // https://doc.iqrf.org/DpaTechGuide/pages/aftersleep.html
      break;

      // -------------------------------------------------
    case DpaEvent_DisableInterrupts:
      // Called when device needs all hardware interrupts to be disabled (before Reset, Restart, LoadCode, Remove bond and run RFPGM)
      // https://doc.iqrf.org/DpaTechGuide/pages/eventDisableInterrupts.html
      break;

      // -------------------------------------------------
    case DpaEvent_PeerToPeer:
      // Called when peer-to-peer (non-networking) packet is received
      // https://doc.iqrf.org/DpaTechGuide/pages/peertopeer.html
      break;

      // -------------------------------------------------
    case DpaEvent_UserDpaValue:
      // Called when DPA is required to return User defined DPA value in the response
      // https://doc.iqrf.org/DpaTechGuide/pages/userdpavalue.html
      break;

      // -------------------------------------------------
#ifdef DpaEvent_InStandby
    case DpaEvent_InStandby:
      // Called to set WDT during Standby
      // https://doc.iqrf.org/DpaTechGuide/pages/instandby.html

      //goto DpaHandleReturnTRUE; // return TRUE to indicate that userReg1 contains WDT settings
      break;
#endif

      // -------------------------------------------------
    case DpaEvent_VerifyLocalFrc:
      // Called to verify local FRC command
      // https://doc.iqrf.org/DpaTechGuide/pages/verifylocalfrc.html

      //goto DpaHandleReturnTRUE; // return TRUE allow FRC command
      break;

      // -------------------------------------------------
#ifdef DpaEvent_MenuActivated
    case DpaEvent_MenuActivated:
      // Called to customize DPA menu
      // https://doc.iqrf.org/DpaTechGuide/pages/menuactivated.html

      //goto DpaHandleReturnTRUE; // return TRUE to allow customizing menu specified by userReg1
      break;
#endif

      // -------------------------------------------------
#ifdef DpaEvent_MenuItemSelected
    case DpaEvent_MenuItemSelected:
      // Called to indicate "OK" or "Error" for selected menu item
      // https://doc.iqrf.org/DpaTechGuide/pages/menuitemselected.html

      //goto DpaHandleReturnTRUE; // return TRUE to indicate "OK" for menu item specified by userReg1, otherwise to indicate Error
      break;
#endif

      // -------------------------------------------------
#ifdef DpaEvent_MenuItemFinalize
    case DpaEvent_MenuItemFinalize:
      // Called to finalize menu item execution
      // https://doc.iqrf.org/DpaTechGuide/pages/menuitemfinalize.html

      break;
#endif

      // -------------------------------------------------
    case DpaEvent_DpaRequest:
      // Called to interpret DPA request for peripherals
      // https://doc.iqrf.org/DpaTechGuide/pages/EventDpaRequest.html
      IfDpaEnumPeripherals_Else_PeripheralInfo_Else_PeripheralRequest()
      {
        // -------------------------------------------------
        // Peripheral enumeration
        // https://doc.iqrf.org/DpaTechGuide/pages/enumerate-peripherals.html

        _DpaMessage.EnumPeripheralsAnswer.UserPerNr |= 0; // ?
        // FlagUserPer( _DpaMessage.EnumPeripheralsAnswer.UserPer, PNUM_USER + 0 ); // ?
        _DpaMessage.EnumPeripheralsAnswer.HWPID |= 0x000F; // ????
        _DpaMessage.EnumPeripheralsAnswer.HWPIDver |= 0; // ????

DpaHandleReturnTRUE:
        return TRUE;
      }
      else
      {
      // -------------------------------------------------
      // Get information about peripheral
      // https://doc.iqrf.org/DpaTechGuide/pages/get-peripheral-info.html

      if ( _PNUM == PNUM_USER + 0 ) // ?
      {
        _DpaMessage.PeripheralInfoAnswer.PerT = 0; // PERIPHERAL_TYPE_?
        _DpaMessage.PeripheralInfoAnswer.PerTE = 0; // PERIPHERAL_TYPE_EXTENDED_?
        _DpaMessage.PeripheralInfoAnswer.Par1 = 0; // ?
        _DpaMessage.PeripheralInfoAnswer.Par2 = 0; // ?
        goto DpaHandleReturnTRUE;
      }

      break;
      }

      // -------------------------------------------------
      // Handle peripheral command
      // https://doc.iqrf.org/DpaTechGuide/pages/handle-peripheral-request.html

      if ( _PNUM == PNUM_USER + 0 ) // ?
      {
        if ( _PCMD == 0 ) // ????
        {
          goto DpaHandleReturnTRUE;
        }
      }

      break;
  }

DpaHandleReturnFALSE:
  return FALSE;
}

//############################################################################################
// Uncomment the following includes if the respective component is needed
//#include "NFC.c"

// Default Custom DPA Handler header; 2nd include implementing a Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup)
#include "DPAcustomHandler.h"
//############################################################################################
